#!/bin/sh

#
# Copyright © 2015-2021 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh gradlew
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions «$var», «${var}», «${var:-default}», «${var+SET}»,
#           «${var#prefix}», «${var%suffix}», and «$( cmd )»;
#         * compound commands having a testable exit status, especially «case»;
#         * various built-in commands including «command», «set», and «ulimit».
#
#   Important for patching:
#
#   (2) This script targets any POSIX shell, so it avoids extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#       The "traditional" practice of packing multiple parameters into a
#       shell-script variable is of limited use in POSIX.  In particular,
#       arrays are not supported as in shell scriptors.
#
#       The "traditional" practice of packing multiple parameters into a
#       shell-script variable is of limited use in POSIX.  In particular,
#       arrays are not supported as in shell scriptors.
#
#       The "traditional" practice of packing multiple parameters into a
#       shell-script variable is of limited use in POSIX.  In particular,
#       arrays are not supported as in shell scriptors.
#
#   Important for injection:
#
#   (3) This script generates a candidate command line from the Gradle
#       invocation, without using arrays.  This is important for the
#       injection of the `--continuous` flag in the Gradle
#       Build Tool specification.
#
#       https://docs.gradle.org/current/userguide/continuous_build.html#section_command_line_injection
#
#   Important for running:
#
#   (4) Avoid obvious display of worrying error messages when this wrapper is
#       executed by a user with a broken setup; instead, show a clear and
#       concise message when Gradle isn't found in the environment, the
#       correct version isn't found, or the system is misconfigured.
#
#   (5) When this wrapper script is executed, the following settings
#       are provided to Gradle:
#
#       GRADLE_OPTS - a Java System Properties provided by the user.
#       JAVA_OPTS - user provided JVM options.
#       GRADLE_USER_HOME - directory where Gradle user cache is located.
#       GRADLE_USER_HOME_DIR - directory where Gradle user cache is located.
#
#   (6) To avoid duplicate builds, the wrapper should be configured to be
#       the "only" entry point for Gradle execution.
#
#   For better output, this script should be run with the --console=plain
#   option, or with Gradle 8+ the --configuration-cache option.
#
#   (7) Many arguments to the command are passed through as-is to Gradle.
#       However, some arguments that are particularly important for the
#       wrapper should be passed through to Gradle explicitly.  Those
#       arguments include:
#       - configuration-cache, --configuration-cache, --no-configuration-cache,
#         --configure-on-demand, --no-configure-on-demand, --daemon,
#         --no-daemon, --foreground, --info, --warning-mode, --stacktrace,
#         --debug, --build-cache, --no-build-cache, --continuous, --no-continuous,
#         -Dgradle.user.home, -Dgradle.project.name, -Djava.home,
#         -Dfile.encoding, -Duser.country, -Duser.language, -Duser.variant,
#         -Duser.timezone
#
#   (8) When the --configuration-cache option is used, the Gradle User Home
#       directory is located in the Gradle installation directory and
#       not in the default location.
#
#   (9) For systems with slow network connections, using a mirror for
#       downloading dependencies is recommended.  The mirror can be set
#       using the following environment variables or system properties:
#       - GRADLE_USER_HOME/bin/gradle/wrapper/gradle-wrapper.properties
#       - GRADLE_USER_HOME/bin/gradle/wrapper/gradle-wrapper.jar
#       - GRADLE_USER_HOME/bin/gradle/wrapper/gradle-wrapper.properties
#
#   (10) When downloading dependencies, the wrapper verifies that the
#       checksum of the downloaded file matches the checksum of the
#       wrapper.properties file.  This helps to prevent the use of compromised
#       Gradle distributions.  For improved security, the wrapper should
#       be used in combination with the Gradle Wrapper Validation Plugin.
#       (https://docs.gradle.org/current/userguide/validation.html).
#
#   (11) When running on systems with old (non-clustered) build tools, the
#       wrapper should be configured to use a shared cache directory for
#       Gradle.  The shared cache directory should be located in a
#       location that is accessible from all machines that run the wrapper.
#
#       For more information on the Gradle Wrapper, please see the Gradle
#       User Manual at https://docs.gradle.org/current/userguide/gradle_wrapper.html.
#       For a more general introduction to the Gradle build system, see
#       https://docs.gradle.org/current/userguide/user_guide.html.
#
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
fi

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
else
    JAVACMD="java"
fi

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "`uname`" in
  CYGWIN* )
    cygwin=true
    ;;
  Darwin* )
    darwin=true
    ;;
  MSYS* | MINGW* )
    msys=true
    ;;
  NONSTOP* )
    nonstop=true
    ;;
esac

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
    [ -n "$JAVA_HOME" ] &&
        JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
    [ -n "$CLASSPATH" ] &&
        CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

# Attempt to set APP_HOME
# Resolve links: $0 may be a link
PRG="$0"
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG=`expr "$PRG" : '\(.*/\)\(.+\)' \| '\(.+\)'`
    fi
done
SAVED="`pwd`"
cd "`dirname "$PRG`" >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

APP_NAME="Gradle"
# This is for Cygwin compatibility.  Cygwin has a habit of leaving
# trailing carriage returns in environment variables that interfere with
# other programs.
APP_HOME=`cygpath --path --mixed "$APP_HOME"`
CLASSPATH=`cygpath --path --mixed "$CLASSPATH"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Collect all arguments for the java command
set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$APP_HOME/gradle/wrapper/gradle-wrapper.jar\"" org.gradle.wrapper.GradleWrapperMain "$@"

# Execute Gradle
exec "$JAVACMD" "$@"